### ISSUE TITLE
Missing AcousticTemplateFixes.esp

### ISSUE THREAD

**Issue by CyborgArmGun** [aglowinthefield/AcousticSpaceImprovementsPatcher#1]
Message:

```
MissingModException Skyrim.esm (+78): 

Missing AcousticTemplateFixes.esp

   at Mutagen.Bethesda.ListsModsMixIn.AssertListsMod(ILoadOrderGetter loadOrder, ModKey modKey, String message)
   at AcousticSpaceImprovementsPatcher.Program.<>c.<Main>b__1_0(IRunnabilityState state) in C:\Users\Anna\AppData\Local\Temp\Synthesis\dhduivxv.cd2\Git\rkg4nkxd.lua\Runner\AcousticSpaceImprovementsPatcher\Program.cs:line 22
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass20_0.<<AddRunnabilityCheck>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 166
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.CheckRunnability(CheckRunnability args, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 187
```

It's in my load order.

**Comment by aglowinthefield** [comment]
Weird, lemme see if I can reproduce it. My first time using that assertion, worked for me though.

**Comment by aglowinthefield** [comment]
@CyborgArmGun It's in your LO, is it enabled? Just checking.

**Comment by tomauty** [comment]
@CyborgArmGun bumping on this, wanna make sure I can fix :)

**Comment by aglowinthefield** [comment]
@CyborgArmGun bumping this, wanna make sure i can fix :)

**Comment by CyborgArmGun** [comment]
I actually dropped the plug in and moved on. I'm busy so I can't guarantee I'll have time to debug it later, sorry.

**Comment by tomauty** [comment]
No worries. I'll close this for now, feel free to reopen if you end up trying again!

**Comment by aglowinthefield** [comment]
Feel free to reopen if you try again and it breaks! :)

**Comment by CyborgArmGun** [comment]
You're on, will do. o/
